# Generated by Django 4.0.4 on 2022-05-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regexentry',
            name='id',
        ),
        migrations.AlterField(
            model_name='regexentry',
            name='name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
