version: "3.9"

services:
  db:
    build: ./db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: database

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: database
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build: ./frontend
    volumes:
    - ./frontend:/app
    ports:
      - "8612:8080"
