version: '2'
services:
  postgres:
    build: ./postgres
    environment:
      POSTGRES_USER: censo
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  metabase:
    image: metabase/metabase:latest
    container_name: metabase-censo
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_HOST: postgres
      MB_DB_PORT: 5432
      MB_DB_USER: censo
      MB_DB_PASS: 123
      MB_DB_DBNAME: metabase